name: Go implementation (CI)
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=GIT_TAG_DESCRIBE::$(git describe --tags)"
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Ensure gofmt
      run: test -z "$(gofmt -s -d .)"
    - name: Ensure go.mod is already tidied
      run: go mod tidy && git diff --no-patch --exit-code
    - name: Run unit tests
      run: go test ./...
    - name: Build with Goreleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --skip-publish --rm-dist
      env:
        GIT_TAG: ${{ steps.get_version.outputs.GIT_TAG_DESCRIBE }}
    - name: Setup BATS framework
      run: sudo npm install -g bats
    - name: kubectx (Go) integration tests
      run: COMMAND=./dist/kubectx_linux_amd64/kubectx bats test/kubectx.bats
    - name: kubens (Go) integration tests
      run: COMMAND=./dist/kubens_linux_amd64/kubens bats test/kubens.bats
