name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=GIT_TAG_DESCRIBE::$(git describe --tags)"
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        GIT_TAG: ${{ steps.get_version.outputs.GIT_TAG_DESCRIBE }}
#    - name: Update new version for plugin 'ctx' in krew-index
#      uses: rajatjindal/krew-release-bot@v0.0.38
#      with:
#        krew_template_file: .krew/ctx.yaml
#    - name: Update new version for plugin 'ns' in krew-index
#      uses: rajatjindal/krew-release-bot@v0.0.38
#      with:
#        krew_template_file: .krew/ns.yaml
